sudo: required
services:
  - docker

before_install:
  - docker build -t santhumsciflex/react-test:1.0 -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true santhumsciflex/react-test:1.0 npm run test -- --coverage

after_success:
  - docker build -t santhumsciflex/multi-client ./client
  - docker build -t santhumsciflex/multi-nginx ./nginx
  - docker build -t santhumsciflex/multi-server ./server
  - docker build -t santhumsciflex/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push santhumsciflex/multi-client
  - docker push santhumsciflex/multi-nginx
  - docker push santhumsciflex/multi-server
  - docker push santhumsciflex/multi-worker

